import type { Metadata } from 'next';

import './globals.css';
import { inter } from '@/libs/configs/fonts';
import Navbar from '@/components/Navbar/Navbar';
import SocialLinks from '@/components/SocialLinks/SocialLinks';
import Footer from '@/components/Footer/Footer';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={`${inter.className} bg-black text-white`}>
        <Navbar />
        <SocialLinks />
        {children}
        <Footer />
      </body>
    </html>
  );
}
